<?php

// Sample script for managing crash reports generated by MailPluginTool
//	Scott Little, based on a script written by
// Tom Harrington, tph@atomicbird.com, May 25 2006
// Updated by Dallas Brown, dbrown@hashbangind.com, June 19 2009 to remove redirect to bypass a bug in Apple's networking code
// Updated by Andy Matuschak, andy@andymatuschak.org, Feb 28 2010 to avoid adding entries when the user does not submit any information. Thanks to Alex Celeste for noticing the bug and submitting a patch.

//	Get the payload first
$payload = file_get_contents("php://input");
$crashLogs = array();

//	Then parse it
if (strlen($payload) > 0) {
	$crashLogs = json_decode($payload, true);
}

require("profileConfig.php");
require("profileDB.php");

$debug = 0;
//	I configure this value inside *my* version of profileConfig.php, so to ensure that a value is set we test here.
if (empty($isTest)) {
	$isTest = 0;
}

if (array_key_exists('report-list', $crashLogs)) {
	// connect to the database
	if (!TryOpenDB()) {
		abortAndExit();
	}
	
	if ($debug) {
		print "<html><head><title>debug</title></head><body>\n";
	}

	//	System Info	
	$systemInfo = $crashLogs['system-info'];
	$systemIdentifier = mysql_real_escape_string($systemInfo['anonymous-id']);

	//	Record the session
	$reportCount = count($crashLogs['report-list']);
	$totalReportCount = mysql_real_escape_string($crashLogs['total-report-count']);
	$queryString = "insert into crashReportSession (ip_addr, session_date, report_count, total_report_count, identifier, hardware, system_version, system_build, mail_version,".
		"mail_build, mail_uuid, message_version, message_build, message_uuid, is_test) values (\"". $_SERVER["REMOTE_ADDR"] ."\",\"". strftime("%Y-%m-%d %H:%M:%S") ."\", ". 
		$reportCount .", ". $totalReportCount .", \"". $systemIdentifier ."\", \"". mysql_real_escape_string($systemInfo['hardware']) ."\", \"". mysql_real_escape_string($systemInfo['system']['version']).
		"\", \"". mysql_real_escape_string($systemInfo['system']['build']) ."\", \"". mysql_real_escape_string($systemInfo['mail']['version']) ."\", \"". 
		mysql_real_escape_string($systemInfo['mail']['build']) ."\", \"". mysql_real_escape_string($systemInfo['mail']['uuid']) ."\", \"". 
		mysql_real_escape_string($systemInfo['message']['version']) ."\", \"". mysql_real_escape_string($systemInfo['message']['build']) ."\", \"". 
		mysql_real_escape_string($systemInfo['message']['uuid']) ."\", ". $isTest .")";
	if ($debug) {
		print "$queryString<br />\n";
	}
	$sqlResult = mysql_query($queryString);
	if (!$sqlResult) {
		abortAndExit();
	}
	//	Get the session id
	$sessionID = mysql_insert_id();
	

	//	Load up all of the plugin information
	$keys = array('installed', 'disabled');
	foreach ($keys as $enabled) {
		$isEnable = 0;
		if ($enabled == 'installed') {
			$isEnable = 1;
		}
		foreach ($systemInfo[$enabled] as $pluginInfo) {
		
			$queryString = "insert into crashReportPlugins (session_id, identifier, name, path, version, build, is_enabled, is_test) values (". $sessionID .", \"". 
				$systemIdentifier ."\", \"". mysql_real_escape_string($pluginInfo['name']) ."\", \"". mysql_real_escape_string($pluginInfo['path']) ."\", \"".
				mysql_real_escape_string($pluginInfo['version']) ."\", \"". mysql_real_escape_string($pluginInfo['build']) ."\", ". $isEnable .", ". $isTest .")";
				
			if ($debug) {
				print "$queryString<br />\n";
			}
			$sqlResult = mysql_query($queryString);
			if (!$sqlResult) {
				abortAndExit();
			}
		}
	}

	
	//	Load the reports
	$inserted_records = 0;
	foreach ($crashLogs['report-list'] as $reportDict) {
		
		// Date, 
		$reportDate = strtotime($reportDict['date']);
		$reportType = mysql_real_escape_string($reportDict['type']);
		$reportBundle = mysql_real_escape_string($reportDict['bundle']);
		$reportContent = mysql_real_escape_string($reportDict['report']);
		$formattedReportDate = strftime("%Y-%m-%d %H:%M:%S", $reportDate);
		
		//	First test to see if this report has already been added
		$testQueryString = "select count(*) from crashReportRecord where identifier = '$systemIdentifier' and report_date = '$formattedReportDate' and report_bundle = '$reportBundle'";
		$result = mysql_query($testQueryString);
		$new_report = false;
		if ($result) {
			$row = mysql_fetch_array($result);
			if ($debug) {
				print "Query was:$testQueryString\n";
				print "Number rows matching this report:". $row[0] ."<br/>\n";
			}
			$new_report = ($row[0] == 0);
		}
	
		//	If we have a new record add it, otherwise just skip		
		if ($new_report) {
			$queryString = "INSERT INTO crashReportRecord (session_id, identifier, report_date, report_bundle, report_type, report_content, is_test) VALUES (". $sessionID .", \"". 
				$systemIdentifier ."\", \"". strftime("%Y-%m-%d %H:%M:%S", $reportDate) ."\", \"". $reportBundle ."\", \"". $reportType ."\", \"". $reportContent ."\", ".$isTest.")";
			if ($debug) {
				print "Report added for $reportBundle - Date:".$reportDict['date']."<br />\n";
			}
			
			$sqlResult = mysql_query($queryString);
			if (!$sqlResult) {
				abortAndExit();
			}
			
			$inserted_records++;
		}
		
	}
	
	//	Update the session with the actual inserted count if it is greater than 0
	if ($inserted_records > 0) {
		$queryString = "update crashReportSession set added_report_count = $inserted_records where session_id = $sessionID";

		$sqlResult = mysql_query($queryString);
		if (!$sqlResult) {
			abortAndExit();
		}
		
	}
	
	CloseDB();
	if ($debug) {
		print "</body>\n";
		exit();
	}

}

header("HTTP/1.1 200 OK");
header("Status: 200 OK");
?>